version: '3.9'

services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cadastro
      - POSTGRES_PASSWORD=cadastro